name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scan-artifacts
          path: .
